// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/tours/tours.proto

package tours

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Poruka za zahtev - sadrži ID ture koju tražimo
type GetTourByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId string `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tours_tours_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *GetTourByIdRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

// Poruka za odgovor - sadrži sve detalje ture
type GetTourByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string           `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Name          string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    int32            `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string         `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string           `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64          `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64          `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"`
	KeyPoints     []*KeyPoint      `protobuf:"bytes,10,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	TransportInfo []*TourTransport `protobuf:"bytes,11,rep,name=transportInfo,proto3" json:"transportInfo,omitempty"` // Polja za vreme ćemo preskočiti za sada radi jednostavnosti
}

func (x *GetTourByIdResponse) Reset() {
	*x = GetTourByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tours_tours_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdResponse) ProtoMessage() {}

func (x *GetTourByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTourByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTourByIdResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetTourByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTourByIdResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTourByIdResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetTourByIdResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetTourByIdResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTourByIdResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetTourByIdResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GetTourByIdResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *GetTourByIdResponse) GetTransportInfo() []*TourTransport {
	if x != nil {
		return x.TransportInfo
	}
	return nil
}

// Pomoćne poruke koje se koriste unutar odgovora
type KeyPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId      string  `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Latitude    float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageUrl    string  `protobuf:"bytes,7,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tours_tours_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type TourTransport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TimeInMinutes int32  `protobuf:"varint,2,opt,name=timeInMinutes,proto3" json:"timeInMinutes,omitempty"`
}

func (x *TourTransport) Reset() {
	*x = TourTransport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tours_tours_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TourTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourTransport) ProtoMessage() {}

func (x *TourTransport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourTransport.ProtoReflect.Descriptor instead.
func (*TourTransport) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *TourTransport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TourTransport) GetTimeInMinutes() int32 {
	if x != nil {
		return x.TimeInMinutes
	}
	return 0
}

var File_proto_tours_tours_proto protoreflect.FileDescriptor

var file_proto_tours_tours_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2f, 0x74, 0x6f,
	0x75, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x6f, 0x75, 0x72, 0x73,
	0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0xe0,
	0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66,
	0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69,
	0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x75, 0x72,
	0x73, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x6f, 0x75, 0x72, 0x73, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x22, 0x49, 0x0a, 0x0d, 0x54, 0x6f, 0x75, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x49,
	0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x32, 0x56, 0x0a,
	0x0c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x74,
	0x6f, 0x75, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tours_tours_proto_rawDescOnce sync.Once
	file_proto_tours_tours_proto_rawDescData = file_proto_tours_tours_proto_rawDesc
)

func file_proto_tours_tours_proto_rawDescGZIP() []byte {
	file_proto_tours_tours_proto_rawDescOnce.Do(func() {
		file_proto_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tours_tours_proto_rawDescData)
	})
	return file_proto_tours_tours_proto_rawDescData
}

var file_proto_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tours_tours_proto_goTypes = []interface{}{
	(*GetTourByIdRequest)(nil),  // 0: tours.GetTourByIdRequest
	(*GetTourByIdResponse)(nil), // 1: tours.GetTourByIdResponse
	(*KeyPoint)(nil),            // 2: tours.KeyPoint
	(*TourTransport)(nil),       // 3: tours.TourTransport
}
var file_proto_tours_tours_proto_depIdxs = []int32{
	2, // 0: tours.GetTourByIdResponse.keyPoints:type_name -> tours.KeyPoint
	3, // 1: tours.GetTourByIdResponse.transportInfo:type_name -> tours.TourTransport
	0, // 2: tours.ToursService.GetTourById:input_type -> tours.GetTourByIdRequest
	1, // 3: tours.ToursService.GetTourById:output_type -> tours.GetTourByIdResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tours_tours_proto_init() }
func file_proto_tours_tours_proto_init() {
	if File_proto_tours_tours_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tours_tours_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTourByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tours_tours_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTourByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tours_tours_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tours_tours_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TourTransport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tours_tours_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tours_tours_proto_goTypes,
		DependencyIndexes: file_proto_tours_tours_proto_depIdxs,
		MessageInfos:      file_proto_tours_tours_proto_msgTypes,
	}.Build()
	File_proto_tours_tours_proto = out.File
	file_proto_tours_tours_proto_rawDesc = nil
	file_proto_tours_tours_proto_goTypes = nil
	file_proto_tours_tours_proto_depIdxs = nil
}
