basePath: /api
definitions:
  domain.Tour:
    properties:
      authorId:
        type: string
      description:
        type: string
      difficulty:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: number
      reviews:
        description: <-- DODATO POLJE
        items:
          $ref: '#/definitions/domain.TourReview'
        type: array
      status:
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - description
    - difficulty
    - name
    type: object
  domain.TourReview:
    properties:
      comment:
        type: string
      commentDate:
        type: string
      id:
        type: string
      imageUrls:
        items:
          type: string
        type: array
      rating:
        maximum: 5
        minimum: 1
        type: integer
      touristId:
        type: string
      visitDate:
        type: string
    required:
    - rating
    - visitDate
    type: object
host: localhost:8083
info:
  contact: {}
  description: API za upravljanje turama.
  title: Tours Service API
  version: "1.0"
paths:
  /tours:
    get:
      description: Vraća listu svih tura dostupnih u sistemu.
      produces:
      - application/json
      responses:
        "200":
          description: Lista svih tura
          schema:
            items:
              $ref: '#/definitions/domain.Tour'
            type: array
      summary: Prikaz svih tura
    post:
      consumes:
      - application/json
      description: Kreira novu turu sa statusom 'draft' i cenom 0. Zahteva autentikaciju.
      parameters:
      - description: Podaci o turi (bez statusa, cene i authorId)
        in: body
        name: tour
        required: true
        schema:
          $ref: '#/definitions/domain.Tour'
      produces:
      - application/json
      responses:
        "201":
          description: Uspešno kreirana tura
          schema:
            $ref: '#/definitions/domain.Tour'
        "400":
          description: 'Greška: Neispravan format zahteva'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 'Greška: Korisnik nije autorizovan'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Kreiranje nove ture
  /tours/{id}/reviews:
    post:
      consumes:
      - application/json
      description: Dodaje novu recenziju na turu sa datim ID-jem. Zahteva autentikaciju.
      parameters:
      - description: ID Ture
        in: path
        name: id
        required: true
        type: string
      - description: Podaci o recenziji
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/domain.TourReview'
      produces:
      - application/json
      responses:
        "200":
          description: Poruka o uspehu
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Dodavanje recenzije na turu
  /tours/my-tours:
    get:
      description: Vraća listu svih tura koje je kreirao autor čiji se token koristi.
      produces:
      - application/json
      responses:
        "200":
          description: Lista tura
          schema:
            items:
              $ref: '#/definitions/domain.Tour'
            type: array
        "401":
          description: 'Greška: Korisnik nije autorizovan'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Prikaz tura kreiranih od strane ulogovanog autora
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
